version: '3'
services:
  jupyter:
    image: jupyter/notebook
    volumes:
      - Jupyter_Notebooks:/notebooks
    command: notebook --no-browser --ip=0.0.0.0 --port=8888
    ports:
      - "8888:8888"